### PR TITLE
OPENMEETINGS-2248 Feature/update website fix link regenerate

### PR DESCRIPTION
**Pull request by sebawagner**
Update link and fix page to CI-management.
Regenerate site fresh.

### CODE REVIEW

**Comment by sebawagner** [comment]
This also fixes the image that is displayed strangely right now for the ASF conference. At least testing locally, after regenerating, it shows up fine.

**Comment by sebawagner** [comment]
I hope this goes into the right branch. Could we delete master branch for this project and make asf-site default ?

**Comment by solomax** [comment]
This is the change I can't review :(
I usually do manual merge

> I hope this goes into the right branch. Could we delete master branch for this project and make asf-site default ?

I guest we can safely do this
Will try

**Review by solomax — APPROVED** [review]

**Comment by sebawagner** [comment]
Seems like the website at https://openmeetings.apache.org/ updated almost instantly with the merge.

**Pull request merged**
