### PR TITLE
Update Build Instructions JavaScript.

### PR DESCRIPTION
**Pull request by sebawagner**
Update JavaScript build instructions.

Prob needs some more details once OM5 is released.

### CODE REVIEW

**Review by solomax — APPROVED** [review]
I wouldn't manually update these pages due to the whole site will be renewed in couple of days :)

**Comment by sebawagner** [comment]
I didn't manually update, I used mvn site. Just not copying over the entire file site but just a subset of files that have been changed.

**Comment by sebawagner** [comment]
Also I would like to test how fast the website updates 😄

**Comment by solomax** [comment]
This should be carefully tested :)))

**Pull request closed without merging**
